"""
L4 Store -- graph.json, graph.cypher, optional live Neo4j ingestion.
graph.json is the git-inspectable source of truth.
graph.cypher is regenerated from graph.json; do not commit.
"""

from __future__ import annotations

import os
from pathlib import Path

from k1_pipeline.models import K1Graph


def write_json(graph: K1Graph, out_dir: Path) -> Path:
    """Write graph.json to out_dir. Returns path."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "graph.json"
    path.write_text(graph.model_dump_json(indent=2))
    return path


def _esc(s: str) -> str:
    return str(s).replace("\\", "\\\\").replace("'", "\\'")


def _props_str(d: dict) -> str:
    parts = []
    for k, v in d.items():
        if v is None:
            continue
        if isinstance(v, bool):
            parts.append(f"{k}: {str(v).lower()}")
        elif isinstance(v, (int, float)):
            parts.append(f"{k}: {v}")
        elif isinstance(v, list):
            # Deduplicate for display only
            unique = list(dict.fromkeys(str(i) for i in v))
            items = ", ".join(f"'{_esc(i)}'" for i in unique)
            parts.append(f"{k}: [{items}]")
        else:
            parts.append(f"{k}: '{_esc(str(v))}'")
    return "{" + ", ".join(parts) + "}"


def _node_to_cypher(node_id: str, labels: list[str], props: dict) -> str:
    label_str = ":".join(labels)
    return f"MERGE (n:{label_str} {{node_id: '{_esc(node_id)}'}}) SET n += {_props_str(props)};"


def write_cypher(graph: K1Graph, out_dir: Path) -> tuple[str, Path]:
    """
    Generate and write graph.cypher.
    Returns (cypher_text, path).
    Use 'k1 store --apply-schema' before ingestion to set up constraints.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "// K1 graph — generated by k1_pipeline store.writer",
        "// Apply schema constraints first: k1 store --apply-schema",
        "",
    ]

    # Process/Transfer/Plate nodes
    for node in graph.nodes:
        props = {
            "node_id": node.node_id,
            "node_type": node.node_type.value,
            "action_phrase": node.action_phrase,
            "canonical_action": node.canonical_action,
            "mean_confidence": round(node.mean_confidence, 4),
            "source_recipe_ids": node.source_recipe_ids,
        }
        if node.timing_constraints and node.timing_constraints.duration_s is not None:
            props["timing_duration_s"] = node.timing_constraints.duration_s
        if node.timing_constraints and node.timing_constraints.deadline:
            props["timing_deadline"] = node.timing_constraints.deadline
        lines.append(_node_to_cypher(node.node_id, [node.node_type.value], props))

    lines.append("")

    # Ingredient nodes
    for ing in graph.ingredient_nodes:
        lines.append(
            f"MERGE (n:Ingredient {{node_id: '{_esc(ing['id'])}'}}) "
            f"SET n += {{name: '{_esc(ing['name'])}', node_id: '{_esc(ing['id'])}'}};"
        )

    lines.append("")

    # Tool nodes
    for tool in graph.tool_nodes:
        lines.append(
            f"MERGE (n:Tool {{node_id: '{_esc(tool['id'])}'}}) "
            f"SET n += {{name: '{_esc(tool['name'])}', node_id: '{_esc(tool['id'])}'}};"
        )

    lines.append("")

    # Safety Bound concept nodes
    seen_bounds: set[str] = set()
    for node in graph.nodes:
        for bound in node.safety_bounds:
            if bound.bound_id not in seen_bounds:
                bp = {
                    "node_id": f"bound_{bound.bound_id}",
                    "bound_id": bound.bound_id,
                    "label": bound.label,
                    "severity": bound.severity,
                }
                if bound.temperature_c is not None:
                    bp["temperature_c"] = bound.temperature_c
                if bound.k2_transition:
                    bp["k2_transition"] = bound.k2_transition
                lines.append(
                    f"MERGE (n:SafetyBound {{node_id: 'bound_{_esc(bound.bound_id)}'}}) "
                    f"SET n += {_props_str(bp)};"
                )
                seen_bounds.add(bound.bound_id)

    lines.append("")

    # Edges
    for edge in graph.edges:
        rel_props = {}
        if edge.source_recipe_id:
            rel_props["source_recipe_id"] = edge.source_recipe_id
        if edge.weight != 1.0:
            rel_props["weight"] = edge.weight
        for k, v in (edge.properties or {}).items():
            if v is not None:
                rel_props[k] = v
        prop_str = f" {_props_str(rel_props)}" if rel_props else ""
        lines.append(
            f"MATCH (a {{node_id: '{_esc(edge.from_node_id)}'}}), "
            f"(b {{node_id: '{_esc(edge.to_node_id)}'}}) "
            f"MERGE (a)-[:{edge.edge_type}{prop_str}]->(b);"
        )

    cypher_text = "\n".join(lines)
    path = out_dir / "graph.cypher"
    path.write_text(cypher_text)
    return cypher_text, path


def ingest_neo4j(
    graph: K1Graph,
    cypher_text: str | None = None,
    schema_path: Path | None = None,
) -> None:
    """
    Ingest graph into a live Neo4j instance.
    Requires NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD in environment.

    Args:
        graph: The K1Graph to ingest.
        cypher_text: Pre-generated Cypher string (avoids /tmp round-trip).
                     If None, the Cypher is generated inline.
        schema_path: Optional path to graph_schema.cypher for applying constraints first.
    """
    try:
        from neo4j import GraphDatabase
    except ImportError:
        print("neo4j package not installed. Run: uv add neo4j")
        return

    uri = os.environ["NEO4J_URI"]
    user = os.environ.get("NEO4J_USERNAME", "neo4j")
    password = os.environ["NEO4J_PASSWORD"]

    # Generate Cypher directly if not provided
    if cypher_text is None:
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            cypher_text, _ = write_cypher(graph, Path(tmp))

    driver = GraphDatabase.driver(uri, auth=(user, password))
    with driver.session() as session:
        # Apply schema constraints first if requested
        if schema_path and schema_path.exists():
            schema = schema_path.read_text()
            for stmt in schema.split(";"):
                stmt = stmt.strip()
                if stmt and not stmt.startswith("//"):
                    try:
                        session.run(stmt)
                    except Exception as e:
                        print(f"  Schema warning: {e}")

        # Ingest graph statements
        for stmt in cypher_text.split(";\n"):
            stmt = stmt.strip().rstrip(";")
            if stmt and not stmt.startswith("//"):
                try:
                    session.run(stmt)
                except Exception as e:
                    print(f"  Warning: {e}")
    driver.close()
    print("  Neo4j ingestion complete.")
